bot_token = "xxx"
db_host = '127.0.0.1'
db_port = 3306
db_user = 'root'
db_password = 'root'
db_name = 'embybot'
bot_name = 'xxx'
api_id = 1234
api_hash = "xxx"
embyurl = 'http://xxx.xxx'
embyapi = 'xxx'
groupid = -100
channelid = -100
admin_list = [1,2,3]
ban_channel_id = -100
line = ''
is_create_by_copy = True
prototype_account_id = 'xxx'
code_prefix = 'xxx-register-'
code_default_expire_hour = 0  # 邀请码默认过期小时数
task_auto_start = False
days_threshold = 30  # 自动删号天数
task_init_hour = 0
task_init_minute = 0
rank_auto_start = True  # 榜单定时任务是否自动开启
rank_img_dir = './img'  # 播放榜单图片文件夹
rank_init_hour = 14  # 播放榜单触发小时
rank_init_minute = 0  # 播放榜单触发分钟
rank_pin = False  # 榜单是否置顶
db_backup_auto_start = True  # 是否开启数据库自动备份
db_docker_mode = True  # 数据库是否为docker启动
db_container_name = 'tg-mysql'  # mysql docker容器名称
db_backup_dir = './backup'  # 数据库备份路径
backup_init_hour = 16  # 备份开始时间 小时
backup_init_minute = 0  # 备份开始时间 分钟
max_backups = 7  # 最大备份数量
log_channel_id = -100  # 日志频道tgid
lib_code_prefix = 'xxxx-library-'
rank_sort_by = 'time'  # 榜单默认排序方式，可选('count','time')
rank_playback_time_show = False  # 是否开启榜单播放时长显示
